kairos/urls.py
""" project urls registration """
from cms.sitemaps import CMSSitemap                                         # type: ignore
from django.conf import settings                                            # type: ignore
from django.conf.urls.i18n import i18n_patterns                             # type: ignore
from django.conf.urls.static import static                                  # type: ignore
from django.contrib import admin                                            # type: ignore
from django.contrib.auth.views import LogoutView                            # type: ignore
from django.contrib.sitemaps.views import sitemap                           # type: ignore
from django.contrib.staticfiles.storage import staticfiles_storage          # type: ignore
from django.contrib.staticfiles.urls import staticfiles_urlpatterns         # type: ignore
from django.urls import include, path                                       # type: ignore
from django.views.generic import RedirectView                               # type: ignore

from mbr_announcements.views import AnnouncementsListView
from mbr_meeting_plugin.views import MemberMeetingAddView
from mbr_messages.views import MemberMessageListView
from kairos.views import (
    MemberEmailSignupView, MembersListView, MemberLoginView,
    member_lang_hide, member_lang_show, signup_email_confirm, signup_paid_confirm)


admin.autodiscover()

favicon_url = staticfiles_storage.url("favicon.ico")

urlpatterns = [
    path('sitemap.xml', sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
    path('favicon.ico', RedirectView.as_view(url=favicon_url)),
]
urlpatterns += i18n_patterns(
    path('accounts/login/', MemberLoginView.as_view(), name='login'),               # overwrite login in auth.urls.py
    path('accounts/logout/', LogoutView.as_view(next_page="/"), name='logout'),     # overwrite logout in auth.urls.py
    # not used because gets redirected to the previous page/referer in kairos/templates/registration/login.html
    path('accounts/profile/', RedirectView.as_view(url="/")),                       # redirect to home after login
    path('accounts/', include('django.contrib.auth.urls')),

    path('signup/member/', MemberEmailSignupView.as_view(), name='signup-member'),  # CMS-page reverse name mbr-signup
    path('signup/confirm/<str:key>/<str:token>/', signup_email_confirm, name='signup-confirm'),
    path('signup/paid/<str:keys>/<str:token>/', signup_paid_confirm, name='signup-paid'),

    path("admin/", admin.site.urls),

    # all url kwargs are slugified with exception to 'announcement-add' which is using capitalized category/action names
    path('announcements/list/', AnnouncementsListView.as_view(), name='announcements-list'),
    path('announcements/add/<str:cat>/<str:act>', AnnouncementsListView.as_view(), name='announcement-add'),
    path('announcements/edit/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-edit'),
    path('announcements/update/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-update'),
    path('announcements/delete/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-delete'),
    path('announcements/show/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-show'),

    path('meetings/update/', MemberMeetingAddView.as_view(), name='meetings-update'),

    path('messages/list/', MemberMessageListView.as_view(), name='messages-list'),
    path('messages/add/', MemberMessageListView.as_view(), name='message-add'),
    path('messages/edit/<int:id>', MemberMessageListView.as_view(), name='message-edit'),
    path('messages/update/<int:id>', MemberMessageListView.as_view(), name='message-update'),
    path('messages/delete/<int:id>', MemberMessageListView.as_view(), name='message-delete'),
    path('messages/show/<int:id>', MemberMessageListView.as_view(), name='message-show'),

    path('members/list/', MembersListView.as_view(), name='members-list'),

    path('member_language_hide/<str:lang>/', member_lang_hide, name='member-lang-hide'),
    path('member_language_show/<str:lang>/', member_lang_show, name='member-lang-show'),

    path('', include('cms.urls')),
)

if settings.DEBUG:  # only needed when using runserver
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

mbr_announcements/models.py
""" models for announcements between members """
from django.conf import settings                            # type: ignore
from django.db import models                                # type: ignore
from filer.fields.image import FilerImageField              # type: ignore

from kairos.utils import member_full_name


class AnnounceCategory(models.Model):
    """ member announcement categories """
    ac_name = models.CharField(max_length=39)
    ac_image = FilerImageField(blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:         # pylint: disable=missing-class-docstring,too-few-public-methods
        verbose_name_plural = "AnnounceCategories"
        constraints = (models.UniqueConstraint(fields=['ac_name'], name='unique_category_name'), )

    def __str__(self):
        return f"{self.__class__.__name__}/{self.ac_name}"


class MemberAnnouncement(models.Model):
    """ member announcements offered or requested/searched by members """
    ma_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ma_announce_category = models.ForeignKey(AnnounceCategory, on_delete=models.CASCADE)
    ma_language = models.CharField(max_length=3, choices=settings.LANGUAGES)
    ma_action = models.CharField(max_length=12)     # e.g. offer/request/rent
    ma_description = models.TextField()
    ma_last_updated = models.DateTimeField(auto_now=True)    # needed for to determine the latest entries/changes

    class Meta:         # pylint: disable=missing-class-docstring,too-few-public-methods
        constraints = (models.UniqueConstraint(fields=['ma_user', 'ma_announce_category', 'ma_language', 'ma_action'],
                                               name='unique_user_category_language_action'), )

    def __str__(self):
        # used as record title in django admin views/lists
        return (f"{self.__class__.__name__}"
                f"@{member_full_name(self.ma_user)}"
                f"={self.ma_language}"
                f"-{self.ma_last_updated}"
                f"/{self.ma_announce_category.ac_name}"
                f"_{self.ma_action}"
                f":{self.ma_description}"
                )

mbr_announcements/views.py
""" announcements views. """
import datetime

from typing import Any, Optional
from urllib.parse import urlparse

from django.contrib.auth.models import User                             # type: ignore
from django.db.models import Q                                          # type: ignore
from django.http import HttpRequest, HttpResponseRedirect               # type: ignore
from django.urls import reverse                                         # type: ignore
from django.utils import timezone                                       # type: ignore
from django.utils.text import slugify                                   # type: ignore
from django.utils.translation import gettext as _, override             # type: ignore
from django.views.generic import ListView                               # type: ignore

from ae.django_utils import set_url_part, requested_language            # type: ignore

from kairos.middleware import HIDDEN_LANG_SESSION_KEY
from kairos.utils import send_chg_notif
from .models import AnnounceCategory, MemberAnnouncement


EXC_CAT_ACT_SEP = '+c+a+'
EXC_ADD_MARKER = 'EmptyMemberAnnouncement'
EXC_ANCHOR_ID_PREFIX = "MAnnAIdP"


def check_change_notification(log_desc: str, rec: MemberAnnouncement, current_user: User, request: HttpRequest,
                              chk_desc: str = "", url: str = "", notify_members: Optional[bool] = True):
    """ check changes on MemberAnnouncement record and send notifications if yes.

    :param log_desc:            announcement description text to be logged/send-in-notification, which is on update the
                                new one and on deletion the actual one.
    :param rec:                 added/updated/deleted announcement record data (author, category and action).
    :param current_user:        record of current user.
    :param request:             http request, needed for error notification.
    :param chk_desc:            old announcement description text on update, unspecified or "" on deletion.
    :param url:                 absolute url to show the announcement (unspecified or "" on deletion).
    :param notify_members:      pass False to not send notifications to all members (only send to MCN_LOGGERS).
    """
    if log_desc != chk_desc or not notify_members:
        with override(rec.ma_language):
            item = _("{ma_cat_name}-{ma_action}-announcement").format(ma_cat_name=rec.ma_announce_category.ac_name,
                                                                      ma_action=rec.ma_action)
            mode = 'deleted' if chk_desc == "" else 'added' if EXC_ADD_MARKER in chk_desc else 'updated'
            send_chg_notif(mode, [log_desc], current_user, request,
                           owner=rec.ma_user, item=item, url=url, notify_members=notify_members)


def extend_context(context: dict[str, Any], request: HttpRequest, **kwargs):
    """ extend context for view and plugin (bundled here to avoid redundancies) """
    context['EXC_ADD_MARKER'] = EXC_ADD_MARKER
    context['EXC_CAT_ACT_SEP'] = EXC_CAT_ACT_SEP
    context['EXC_ANCHOR_ID_PREFIX'] = EXC_ANCHOR_ID_PREFIX
    context['url_kwargs'] = kwargs

    context['user_cat_acts'] = user_cat_acts = []  # in order to prevent duplicate member announcements per user
    current_user = request.user
    if current_user.is_authenticated:
        for ma_object in MemberAnnouncement.objects.filter(ma_user=current_user):
            user_cat_acts.append(ma_object.ma_announce_category.ac_name + EXC_CAT_ACT_SEP + ma_object.ma_action)


def get_queryset(request: HttpRequest):
    """ get full/filtered queryset of announcements/objects for view and plugin, bundled here to avoid redundancies. """
    current_user = request.user
    obj_list = MemberAnnouncement.objects

    user_filter = {}
    search_txt = request.GET.get('q')
    if search_txt:
        if search_txt.isnumeric():  # entered member id?
            user_filter['ma_user__username'] = search_txt
        else:
            user_filter['ma_description__contains'] = search_txt
    if request.GET.get('l') == '1':
        user_filter['ma_language'] = requested_language()
    if request.GET.get('u') == '1':
        user_filter['ma_user'] = current_user
    if user_filter:
        if current_user.is_staff:   # admins are seeing all the empty records added/owned by other users
            obj_list = obj_list.filter(Q(**user_filter) | Q(ma_description__contains=EXC_ADD_MARKER))
        else:
            obj_list = obj_list.filter(**user_filter)

    if current_user.is_anonymous:   # not current_user.is_authenticated (prevent 'AnonymousUser' object is not iterable)
        obj_list = obj_list.exclude(ma_description__contains=EXC_ADD_MARKER)
    elif not current_user.is_staff:  # only admins are seeing records added/owned by other users
        obj_list = obj_list.exclude(Q(ma_description__contains=EXC_ADD_MARKER) & ~Q(ma_user=current_user))

    # hide announcements of members that either were not logged in within the last year or were never logged in
    last_year_datetime = timezone.now() - datetime.timedelta(days=365)
    obj_list = obj_list.exclude(Q(ma_user__last_login=None) | Q(ma_user__last_login__lt=last_year_datetime))

    if hidden_languages := request.session.get(HIDDEN_LANG_SESSION_KEY, []):
        obj_list = obj_list.exclude(ma_language__in=hidden_languages)

    return obj_list.order_by("ma_announce_category__ac_name", "ma_action", "-ma_last_updated")


class AnnouncementsListView(ListView):
    """ collapsible list of member announcement actions, plus inline editing, deleting and adding them. """
    model = MemberAnnouncement

    def get_context_data(self, **kwargs):
        """ context data """
        context = super().get_context_data(**kwargs)
        # noinspection PyTypeChecker
        extend_context(context, self.request, **self.kwargs)
        return context

    def get_queryset(self):
        """ filter by currently selected language and order by category-name, action and newest changes first. """
        return get_queryset(self.request)

    def post(self, request: HttpRequest, *_args, **kwargs):
        """ handle member announcements add, delete and change of description. """
        current_user = request.user
        ma_id: Optional[int] = kwargs.get('id')
        if not ma_id:
            cat_name, ma_action, ma_user = kwargs['cat'], kwargs['act'], current_user
            row = MemberAnnouncement.objects.create(
                ma_user=ma_user,
                ma_announce_category=AnnounceCategory.objects.get(ac_name=cat_name),
                ma_language=MemberAnnouncement.objects.filter(ma_action=ma_action).first().ma_language,
                ma_action=ma_action,
                ma_description=f"{ma_user}@{datetime.datetime.now()}+{cat_name}/{ma_action}={EXC_ADD_MARKER}",
            )
            # pylint: enable=no-member # false positive .objects
            ma_id = row.pk
            url = reverse('announcement-edit', kwargs={'cat': slugify(cat_name), 'id': ma_id})

        else:
            cat_slug = kwargs['cat']
            notify_members = request.POST.get(f'notify_members_{ma_id}') == 'on'
            if request.path.split("/")[-3] == 'delete':
                del_rec = MemberAnnouncement.objects.get(id=ma_id)
                pre_rec = self.get_queryset().filter(ma_last_updated__lt=del_rec.ma_last_updated).first()
                if pre_rec:
                    ma_id = pre_rec.pk
                    url = reverse('announcement-show', kwargs={'cat': cat_slug, 'id': ma_id})
                else:
                    ma_id = 0
                    url = reverse('announcements-list')
                if EXC_ADD_MARKER not in (desc := del_rec.ma_description) and desc.strip():
                    check_change_notification(desc, del_rec, current_user, request, notify_members=notify_members)
                del_rec.delete()

            else:  # update
                url = reverse('announcement-show', kwargs={'cat': cat_slug, 'id': ma_id})
                upd_rec = MemberAnnouncement.objects.get(id=ma_id)
                old_desc = upd_rec.ma_description       # old rec desc gets changed by .update(ma_description=...)
                new_desc = request.POST['ma_description'].strip()
                if new_desc:
                    upd_rec.ma_description = new_desc
                    upd_rec.save()
                    check_change_notification(
                        new_desc, upd_rec, current_user, request,
                        chk_desc=old_desc,
                        url=set_url_part(request.build_absolute_uri(url), EXC_ANCHOR_ID_PREFIX + str(ma_id)),
                        notify_members=notify_members)

        url = set_url_part(url, EXC_ANCHOR_ID_PREFIX + str(ma_id), urlparse(request.META.get('HTTP_REFERER')).query)

        return HttpResponseRedirect(url)

mbr_announcements/templates/memberannouncement_plugin.html
{% load i18n kairos_tags %}

{% with can_add=perms.mbr_announcements.add_memberannouncement %}
{% with can_chg=perms.mbr_announcements.change_memberannouncement %}
{% with can_del=perms.mbr_announcements.delete_memberannouncement %}
<div class="container">
    <div class="row">
        <div class="col-1 col-lg-9"></div>
        <div class="col-11 col-lg-3">
            {% include "./mbr_announcements/memberannouncement_filters.html" %}
            {# {% include "./mbr_announcements/memberannouncement_collapse_expand_buttons.html" with position="top" %}#}
        </div>
    </div>
{% cycle 'bg-success' 'bg-primary' 'bg-warning' as act_col silent %}
{% for exc in object_list %}
{% with cat_name=exc.ma_announce_category.ac_name ma_act=exc.ma_action ma_desc=exc.ma_description %}
    {% ifchanged cat_name %}
        {% if not forloop.first %}
        </div>                                                                      {# #excCat{{ cat_name|slugify }} #}
        {% endif %}
        {% resetcycle act_col %}
        <div class="row mt-3 py-lg-3 align-items-start">
            <div class="col-12 col-lg-6">
                <button class="btn btn-lg btn-info btn-block" type="button" data-toggle="collapse"
                        data-target=".multi-collapse{{ cat_name|slugify }}"
                        title="{% translate "Category" %} `{{ cat_name }}` {% translate "Expand/collapse" %}"
                        aria-expanded="false"
                        aria-controls="excCat{{ cat_name|slugify }} excImg{{ cat_name|slugify }}">
                    {{ cat_name }}
                </button>
            </div>
            <div class="col-12 col-lg-6 pt-1 pt-lg-5 collapse multi-collapse{{ cat_name|slugify }} all-collapse
                        {% if request.GET.q or url_kwargs.cat == cat_name|slugify %} show{% endif %}"
                 id="excImg{{ cat_name|slugify }}">
                <img src="{{ exc.ma_announce_category.ac_image.url }}" class="img-fluid rounded shadow"
                     alt="{{ cat_name }} announcement category">
            </div>
        </div>
        <div class="container mb-3 collapse multi-collapse{{ cat_name|slugify }} all-collapse
                    {% if request.GET.q or url_kwargs.cat == cat_name|slugify %} show{% endif %}"
             id="excCat{{ cat_name|slugify }}">
    {% endifchanged %}                                                            {# cat_name #}
    {% ifchanged cat_name ma_act %}
        {% cycle act_col %}
        <div class="row py-3">
            <div class="col-1">
                {% if request.GET.l != '1' %}
                    <span class="{% flag_icon exc.ma_language %}" style="font-size: 1.5rem;"></span>
                {% endif %}
            </div>
            <div class="col-3 p-1 text-white {{ act_col }}">
                {{ ma_act }}
            </div>
            <div class="col-3">
                {% if not user.is_staff and can_add and cat_name|add:EXC_CAT_ACT_SEP|add:ma_act not in user_cat_acts %}
                    <form>
                        {% csrf_token %}
                        <input class="btn btn-outline-info btn-sm" type="submit" value="{% translate "Add" %}"
                               formaction="{% url 'announcement-add' cat_name ma_act %}" formmethod="post"
                               title="{% blocktranslate %}add {{ ma_act }} in {{ cat_name }}{% endblocktranslate %}">
                    </form>
                {% endif %}
            </div>
            <div class="col-0 col-lg-5">
            </div>
        </div>
    {% endifchanged %}                                                        {# cat_name ma_act #}
    {% if url_kwargs.id == exc.pk %}<a id="{{ EXC_ANCHOR_ID_PREFIX }}{{ exc.pk }}"></a>{% endif %}
    <div class="row">
        <div class="col-0 col-lg-2"></div>
        {% if user.is_authenticated %}
            <div class="col-12 col-lg-3 text-lg-right" style="overflow: hidden">
                <a href="tel:{{ exc.ma_user.last_name }}"><strong title="{{ exc.ma_user.last_name }}"
                >{% full_name exc.ma_user %}</strong></a>
            </div>
        {% endif %}
        <div class="col-12 col-lg-{% if user.is_authenticated %}7{% else %}10{% endif %} pb-3">
            {% if user.is_staff or can_chg and user.id == exc.ma_user.id %}
                <form method="post">
                    {% csrf_token %}
                    <!--suppress HtmlFormInputWithoutLabel -->
                    <textarea name="ma_description" class="form-control text-area-auto-height"
                              title="{% blocktranslate %}text of {{ ma_act }} in {{ cat_name }}{% endblocktranslate %}"
                              placeholder="{% blocktranslate %}({{ ma_act }} in {{ cat_name }}){% endblocktranslate %}"
                              style="min-width: 100%"
                    >{% if EXC_ADD_MARKER not in ma_desc or user.is_staff %}{{ ma_desc }}{% endif %}</textarea>
                    <input id="notify_members_{{ exc.pk }}" type="checkbox" name="notify_members_{{ exc.pk }}" checked>
                    <label
                       for="notify_members_{{ exc.pk }}" class="col-form-label">{% translate "Notify members" %}</label>
                    {% if can_del %}
                        <input class="btn btn-outline-info btn-sm" type="submit" value="{% translate "Delete" %}"
                               formaction="{% url 'announcement-delete' cat_name|slugify exc.id %}"
                               title="{% blocktranslate %}delete {{ ma_act }} in {{ cat_name }}{% endblocktranslate %}">
                    {% endif %}
                    <input class="btn btn-outline-info btn-sm" type="submit" value="{% translate "Save" %}"
                           formaction="{% url 'announcement-update' cat_name|slugify exc.id %}"
                           title="{% blocktranslate %}save {{ ma_act }} in {{ cat_name }}{% endblocktranslate %}">
                </form>
            {% else %}
                <div class="border-bottom"
                     style="white-space: pre-wrap;">{{ ma_desc|linebreaksbr }}</div>
            {% endif %}
        </div>
    </div>
{% endwith %}{% empty %}
    <div class="row">
        <div class="col text-center">
            <pre>xvx xvx xvx      {% translate "Empty" %}      xvx xvx xvx</pre>
        </div>
    </div>
{% endfor %}
    {% if object_list %}
    </div>                                                                      {# #excCat{{ cat_name|slugify }} #}
    {% endif %}
    <div class="row mt-5">
        <div class="col-1 col-lg-9"></div>
        <div class="col-11 col-lg-3">
            {% include "./mbr_announcements/memberannouncement_collapse_expand_buttons.html" with position="bottom" %}
        </div>
    </div>
</div>                                                                          {# content container #}
{% endwith %}{% endwith %}{% endwith %}