kairos/urls.py
""" project urls registration """
from cms.sitemaps import CMSSitemap                                         # type: ignore
from django.conf import settings                                            # type: ignore
from django.conf.urls.i18n import i18n_patterns                             # type: ignore
from django.conf.urls.static import static                                  # type: ignore
from django.contrib import admin                                            # type: ignore
from django.contrib.auth.views import LogoutView                            # type: ignore
from django.contrib.sitemaps.views import sitemap                           # type: ignore
from django.contrib.staticfiles.storage import staticfiles_storage          # type: ignore
from django.contrib.staticfiles.urls import staticfiles_urlpatterns         # type: ignore
from django.urls import include, path                                       # type: ignore
from django.views.generic import RedirectView                               # type: ignore

from mbr_announcements.views import AnnouncementsListView
from mbr_meeting_plugin.views import MemberMeetingAddView
from mbr_messages.views import MemberMessageListView
from kairos.views import (
    MemberEmailSignupView, MembersListView, MemberLoginView,
    member_lang_hide, member_lang_show, signup_email_confirm, signup_paid_confirm)


admin.autodiscover()

favicon_url = staticfiles_storage.url("favicon.ico")

urlpatterns = [
    path('sitemap.xml', sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
    path('favicon.ico', RedirectView.as_view(url=favicon_url)),
]
urlpatterns += i18n_patterns(
    path('accounts/login/', MemberLoginView.as_view(), name='login'),               # overwrite login in auth.urls.py
    path('accounts/logout/', LogoutView.as_view(next_page="/"), name='logout'),     # overwrite logout in auth.urls.py
    # not used because gets redirected to the previous page/referer in kairos/templates/registration/login.html
    path('accounts/profile/', RedirectView.as_view(url="/")),                       # redirect to home after login
    path('accounts/', include('django.contrib.auth.urls')),

    path('signup/member/', MemberEmailSignupView.as_view(), name='signup-member'),  # CMS-page reverse name mbr-signup
    path('signup/confirm/<str:key>/<str:token>/', signup_email_confirm, name='signup-confirm'),
    path('signup/paid/<str:keys>/<str:token>/', signup_paid_confirm, name='signup-paid'),

    path("admin/", admin.site.urls),

    # all url kwargs are slugified with exception to 'announcement-add' which is using capitalized category/action names
    path('announcements/list/', AnnouncementsListView.as_view(), name='announcements-list'),
    path('announcements/add/<str:cat>/<str:act>', AnnouncementsListView.as_view(), name='announcement-add'),
    path('announcements/edit/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-edit'),
    path('announcements/update/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-update'),
    path('announcements/delete/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-delete'),
    path('announcements/show/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-show'),

    path('meetings/update/', MemberMeetingAddView.as_view(), name='meetings-update'),

    path('messages/list/', MemberMessageListView.as_view(), name='messages-list'),
    path('messages/add/', MemberMessageListView.as_view(), name='message-add'),
    path('messages/edit/<int:id>', MemberMessageListView.as_view(), name='message-edit'),
    path('messages/update/<int:id>', MemberMessageListView.as_view(), name='message-update'),
    path('messages/delete/<int:id>', MemberMessageListView.as_view(), name='message-delete'),
    path('messages/show/<int:id>', MemberMessageListView.as_view(), name='message-show'),

    path('members/list/', MembersListView.as_view(), name='members-list'),

    path('member_language_hide/<str:lang>/', member_lang_hide, name='member-lang-hide'),
    path('member_language_show/<str:lang>/', member_lang_show, name='member-lang-show'),

    path('', include('cms.urls')),
)

if settings.DEBUG:  # only needed when using runserver
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

mbr_messages/models.py
""" member messages app models """
from django.conf import settings                            # type: ignore
from django.db import models                                # type: ignore

from kairos.utils import member_full_name


class MemberMessage(models.Model):
    """ member messages model """
    mm_author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mm_language = models.CharField(max_length=3, choices=settings.LANGUAGES)
    mm_text = models.TextField()
    mm_public = models.BooleanField()
    mm_expired = models.DateField(null=True, blank=True)
    mm_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # used as record title in django admin views/lists
        return (f"{self.__class__.__name__}"
                f"@{member_full_name(self.mm_author)}"
                f"={self.mm_language}"
                f"-{self.mm_created}"
                + (f"->{self.mm_expired}" if self.mm_expired else "")
                + ("/public" if self.mm_public else "")
                + f":{self.mm_text}"
                )

mbr_messages/views.py
""" member messages views """
import datetime
import re

from typing import Any, Optional
from urllib.parse import urlparse

from django.contrib.auth.models import User                     # type: ignore
from django.db.models import Q                                  # type: ignore
from django.http import HttpRequest, HttpResponseRedirect       # type: ignore
from django.urls import reverse                                 # type: ignore
from django.utils.translation import gettext as _               # type: ignore
from django.views.generic import ListView                       # type: ignore

from ae.django_utils import set_url_part                        # type: ignore

from kairos.middleware import HIDDEN_LANG_SESSION_KEY
from kairos.utils import send_chg_notif
from mbr_messages.models import MemberMessage


MSG_ADD_MARKER = "EmptyMemberMessage"
MSG_ANCHOR_ID_PREFIX = "MMsgAIdP"

MOBILE_AGENT_RE = re.compile(r".*(iphone|mobile|androidtouch)", re.IGNORECASE)


def check_change_notification(old_public: bool, old_expired: Optional[datetime.date], old_lang: str, old_text: str,
                              new_public: bool, new_expired: Optional[datetime.date], new_lang: str, new_text: str,
                              current_user: User, author: User, url: str, notify_members: bool, request: HttpRequest):
    """ check for changes and if yes then send notifications to receivers.

    :param old_public:          old publication status of message.
    :param old_expired:         old message expiry date or None.
    :param old_lang:            old message language.
    :param old_text:            old message text.
    :param new_public:          new publication status.
    :param new_expired:         new expire date or None.
    :param new_lang:            new message language.
    :param new_text:            new message text.
    :param current_user:        user record of currently authenticated user.
    :param author:              user record of message author.
    :param url:                 absolute url to show the changed message on the website.
    :param notify_members:      pass False to not send notifications to all members (only send to MCN_LOGGERS).
    :param request:             http request, needed for error notification.
    """
    action = 'added' if MSG_ADD_MARKER in old_text else 'updated'
    changes = []
    if action == 'added':
        item = _("public message") if new_public else _("private message")
        if new_expired:
            item += " " + _("expiring {new_expired}").format(new_expired=new_expired)
        changes.append(new_text)
    else:
        item = _("message")
        prefix = "- "

        if old_public != new_public:
            changes.append(prefix + (_("made public") if new_public else _("revoked publication")))

        if old_expired != new_expired:
            if not old_expired:
                changes.append(prefix + _("added expiry date {new_expired}").format(new_expired=new_expired))
            elif not new_expired:
                changes.append(prefix + _("removed expiry date {old_expired}").format(old_expired=old_expired))
            else:
                changes.append(prefix + _("changed expiry date from {old_expired} to {new_expired}").format(
                    old_expired=old_expired, new_expired=new_expired))

        if old_lang != new_lang:
            changes.append(prefix + _("changed language from {old_lang} to {new_lang}").format(
                old_lang=old_lang, new_lang=new_lang))

        if old_text != new_text:
            changes.append(new_text)

    if changes or not notify_members:
        send_chg_notif(action, changes, current_user, request,
                       owner=author, item=item, url=url, notify_members=notify_members)


def extend_context(context: dict[str, Any], request: HttpRequest, **kwargs):
    """ extend context for view and plugin (to avoid redundancies) """
    context['MSG_ADD_MARKER'] = MSG_ADD_MARKER
    context['MSG_ANCHOR_ID_PREFIX'] = MSG_ANCHOR_ID_PREFIX
    context['is_mobile'] = MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT'])
    context['url_kwargs'] = kwargs


def get_queryset(request: HttpRequest):
    """ get queryset of all objects for view and plugin (to avoid redundancies). """
    obj_list = MemberMessage.objects

    current_user = request.user
    if current_user.is_anonymous:   # not current_user.is_authenticated (prevent 'AnonymousUser' object is not iterable)
        obj_list = obj_list.exclude(mm_text__contains=MSG_ADD_MARKER).filter(mm_public=True)
    elif not current_user.is_staff:  # only admins are seeing records added/owned by other users
        obj_list = obj_list.exclude(Q(mm_text__contains=MSG_ADD_MARKER) & ~Q(mm_author=current_user))

    if hidden_languages := request.session.get(HIDDEN_LANG_SESSION_KEY, []):
        obj_list = obj_list.exclude(mm_language__in=hidden_languages)

    return obj_list.order_by("-mm_created")


class MemberMessageListView(ListView):
    """ member messages list view """
    model = MemberMessage

    def get_context_data(self, **kwargs):
        """ context data """
        context = super().get_context_data(**kwargs)
        extend_context(context, self.request, **self.kwargs)
        return context

    def get_queryset(self):
        """ filter by currently selected language and order by category-name, action and newest changes first. """
        return get_queryset(self.request)

    def post(self, request: HttpRequest, *_args, **kwargs):
        """ handle member message edit. """
        current_user = request.user
        mm_id: Optional[int] = kwargs.get('id')
        if not mm_id:   # action == 'add'
            row = MemberMessage.objects.create(
                mm_author=current_user,
                mm_language=request.LANGUAGE_CODE,
                mm_public=False,
                mm_text=f"{current_user}@{datetime.datetime.now()}={MSG_ADD_MARKER}",
            )
            mm_id = row.pk
            url = reverse('message-edit', kwargs={'id': mm_id})

        else:
            notify_members = request.POST.get(f'notify_members_{mm_id}') == 'on'
            if request.path.split("/")[-2] == 'delete':
                rec = MemberMessage.objects.get(id=mm_id)
                pre_rec = self.get_queryset().filter(mm_created__lt=rec.mm_created).first()
                if pre_rec:
                    mm_id = pre_rec.pk
                    url = reverse('message-show', kwargs={'id': mm_id})
                else:
                    mm_id = 0
                    url = reverse('messages-list')
                if MSG_ADD_MARKER not in (txt := rec.mm_text) and txt.strip():
                    send_chg_notif('deleted', ([f"- {rec.mm_expired}"] if rec.mm_expired else []) + [txt],
                                   current_user, request,
                                   owner=rec.mm_author,
                                   item=_("public message") if rec.mm_public else _("private message"),
                                   notify_members=notify_members)
                rec.delete()

            else:   # == 'update'
                url = reverse('message-show', kwargs={'id': mm_id})
                rec = MemberMessage.objects.get(id=mm_id)
                old_public, old_expired, old_lang, old_text = (
                    rec.mm_public, rec.mm_expired, rec.mm_language, rec.mm_text)
                new_public, new_expired, new_lang, new_text = (
                    request.POST.get('mm_public') == 'on',      # if checked: 'on', None/not-in-POST-dict if unchecked
                    request.POST['mm_expired'] and datetime.date.fromisoformat(request.POST['mm_expired']) or None,
                    request.POST['mm_language'],
                    request.POST['mm_text'].strip())

                if new_text:    # prevent to wipe the text
                    rec.mm_public, rec.mm_expired, rec.mm_language, rec.mm_text = (
                        new_public, new_expired, new_lang, new_text)
                    rec.save()
                    check_change_notification(
                        old_public, old_expired, old_lang, old_text,
                        new_public, new_expired, new_lang, new_text,
                        current_user, rec.mm_author,
                        set_url_part(request.build_absolute_uri(url), MSG_ANCHOR_ID_PREFIX + str(mm_id)),
                        notify_members, request)

        url = set_url_part(url, MSG_ANCHOR_ID_PREFIX + str(mm_id), urlparse(request.META.get('HTTP_REFERER')).query)

        return HttpResponseRedirect(url)

mbr_messages/templates/mbr_messages/membermessage_edit.html
{% load i18n kairos_tags %}

<div class="row mb-3 px-2 py-3 border border-info rounded-lg shadow">
    <form class="w-100">
        {% csrf_token %}
        <div class="row form-group">
            <div class="col-12 col-lg-2">
                <span class="ml-3" title="{{ msg.mm_author.last_name }}">{% full_name msg.mm_author %}</span>
            </div>
            <div class="col-12 col-lg-1 mx-1">
                <label for="is_public"
                       class="col-form-label font-italic font-weight-lighter" style="font-size: 81%">
                    {% translate "is published" %}
                </label>
                <input id="is_public" type="checkbox" name="mm_public"{% if msg.mm_public %} checked{% endif %}
                       class="form-control"
                       title="{% translate "check to show this message publicly to any visitor of this website" %}">
            </div>
            <div class="col-12 col-lg-2 mx-1">
                <label for="expired_date"
                       class="col-form-label font-italic font-weight-lighter" style="font-size: 81%">
                    {% translate "expire date" %}
                </label>
                <input id="expired_date" type="date" name="mm_expired" value="{{ msg.mm_expired|date:"c" }}"
                       min="{% now 'Y-m-d' %}"
                       class="form-control"
                       title="{% translate "enter the date until this message will be visible in the website news" %}">
            </div>
            <div class="col-12 col-lg-1 mx-1">
                <label for="message_language"
                       class="col-form-label font-italic font-weight-lighter" style="font-size: 81%">
                    {% translate "Language" %}
                </label>
                <select id="message_language" name="mm_language" class="form-control" required
                       title="{% translate "Language" %}">
                  {% for flt in LANGUAGES %}{% with mlc=msg.mm_language fls=flt.0|slice:':2' %}
                    <option value="{{ fls }}" {% if mlc == fls %}selected{% endif %}>{{ flt.1 }}</option>
                  {% endwith %}{% endfor %}
                </select>
            </div>
            <div class="col-12 col-lg-5 mx-1">
                <label for="message_text"
                       class="col-form-label font-italic font-weight-lighter" style="font-size: 81%">
                    {% translate "Text" %}
                </label>
                <!--suppress HtmlFormInputWithoutLabel -->
                <textarea id="message_text" name="mm_text" class="form-control text-area-auto-height"
                          title="{% translate "text of this member message" %}"
                          placeholder="{% translate "(enter new member message text)" %}"
                          style="min-width: 100%"
                >{% if MSG_ADD_MARKER not in msg.mm_text or user.is_staff %}{{ msg.mm_text }}{% endif %}</textarea>
            </div>
        </div>
        <div class="row pt-1">
            <div class="col-12 col-lg-5 ml-1 ml-lg-3">
                <input id="notify_members_{{ msg.pk }}" type="checkbox" name="notify_members_{{ msg.pk }}" checked><label
                      for="notify_members_{{ msg.pk }}" class="col-form-label">{% translate "Notify members" %}</label>
            </div>
            <div class="col-6 col-lg-3">
            {% if perms.mbr_messages.delete_membermessage %}
                <input class="btn btn-outline-info btn-sm" type="submit" value="{% translate "Delete" %}"
                       formaction="{% url 'message-delete' msg.pk %}" formmethod="post"
                       title="{% translate "delete this member message" %}">
            {% endif %}
            </div>
            <div class="col-6 col-lg-3">
                <input class="btn btn-outline-info btn-sm" type="submit" value="{% translate "Save" %}"
                       formaction="{% url 'message-update' msg.pk %}#{{ MSG_ANCHOR_ID_PREFIX }}{{ msg.pk }}"
                       formmethod="post"
                       title="{% translate "save any changes done to this member message" %}">
            </div>
        </div>
    </form>
</div>

mbr_messages/templates/mbr_messages/membermessage_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "Messages" %} - {% translate "KairosBrandName" %}{% endblock %}

{% block content %}
    {% include "../membermessage_plugin.html" %}
{% endblock %}